version: '3.8'

services:
#  myapp:
#    build: .
#    environment:
#      DATABASE_URL: jdbc:postgresql://db:5432/lottery
#    ports:
#      - "8888:8081"
#    depends_on:
#      - db

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lottery
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/